repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: validate-attributes
        name: validate attributes
        entry: bash -c 'PYTHONPATH=. python scripts/validate_attributes.py'
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: bash -c 'STEAM_API_KEY=test pytest'
        language: system
        pass_filenames: false
# Temporarily disabled due to network blocks
# - repo: https://github.com/awslabs/git-secrets
#   rev: 1.3.0
#   hooks:
#     - id: git-secrets
# Hook requires external repo; disable while network access limited
# - repo: https://github.com/antonbabenko/pre-commit-terraform
#   rev: v1.84.0
#   hooks:
#     - id: detect-private-keys
